##
##        (C) COPYRIGHT Ingenic Limited.
##             ALL RIGHTS RESERVED
##
## File       : Makefile
## Authors    : hxu@ingenic.st.jz.com
## Create Time: 2020-08-26:11:37:35
## Description:
##


## Makefile
result : analyse.c
	gcc -o result analyse.c
