##
##        (C) COPYRIGHT Ingenic Limited.
##             ALL RIGHTS RESERVED
##
## File       : Makefile
## Authors    : hxu@ingenic.st.jz.com
## Create Time: 2020-08-31:16:03:59
## Description:
##


## Makefile

run :  simplify.c
	gcc -o run simplify.c
